export declare const DEFAULT_USER_AGENT: string;
export declare const SYMBOL_RAW: symbol;
export declare const SYMBOL_PACKED_OPTIONS: symbol;
export declare const SYMBOL_PACKED: symbol;
export declare const DEFAULT_HTML = "<html><head></head><body></body></html>";
export declare const DEFAULT_HTML2 = "<!doctype html><html><head><meta charset=\"utf-8\"></head><body></body></html>";
export declare const RUN_SCRIPTS_DANGEROUSLY = "dangerously";
export declare const RUN_SCRIPTS_OUTSIDE_ONLY = "outside-only";
import * as self from './const';
export default self;
