"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const package_json_1 = require("../package.json");
exports.DEFAULT_USER_AGENT = `Mozilla/5.0 (${process.platform}) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/${package_json_1.version}`;
exports.SYMBOL_RAW = Symbol.for('SYMBOL_RAW');
exports.SYMBOL_PACKED_OPTIONS = Symbol.for('SYMBOL_PACKED_OPTIONS');
exports.SYMBOL_PACKED = Symbol.for('SYMBOL_PACKED');
exports.defaultHtml = '<html><head></head><body></body></html>';
exports.defaultHtml2 = '<!doctype html><html><head><meta charset="utf-8"></head><body></body></html>';
const self = require("./const");
exports.default = self;
